### PR TITLE
Rust 1.17.0

### PR DESCRIPTION
**Pull request by rillian**
Firefox bumped their minimum so workarounds can be dropped.

https://bugzilla.mozilla.org/show_bug.cgi?id=1374807

---
This change is [Reviewable](https://reviewable.io/reviews/servo/unicode-bidi/41)

### CODE REVIEW

**Comment by mbrubeck** [comment]
Since this crate has a lot of downstream users besides Firefox, we should document some expectations about when it can break for users of older Rust toolchains. One option is to treat changes like this as a semver-breaking change, so that a minor update will never break an existing build.  Another option is to document a support policy like "current stable release and previous 2 stable releases."

**Comment by rillian** [comment]
Gecko will probably move closer to requiring current stable or previous stable, but documenting that requirement is a good idea.

**Comment by behnam** [comment]
I think the idea is that "minimum rustc/rust-lang version required" is a package matter, and should be defined somewhere in the package metadata, versus the implicit annotation in `travis.yml`, or somewhere in a dependent package (Firefox, in this case).

Here's the Cargo discussion: https://github.com/rust-lang/cargo/issues/2751

**Comment by mbrubeck** [comment]
My point is that we should consider consumers besides Gecko, too.

**Comment by rillian** [comment]
Sorry, I didn't mean to say Gecko was the only driver. Of course crates should consider the needs of everyone who depends on them. I just wanted to say we're planning to update Gecko's minimum more frequently, so that doesn't have the a limiting factor.

**Comment by behnam** [comment]
(I'm new to Rust-Gecko and related projects, so it may be obvious, so asking anyway.)

Based on this fact that Gecko is not the only driver, I assume these libraries can move at their own pace and only increase the minimum-rustc-version as needed. Then, if so, was there any need for this diff in the Rust-Gecko build process?

**Comment by mbrubeck** [comment]
No, this was just a cleanup.  It removed code that was *previously* necessary to support the version of Rust used in Gecko.

**Pull request merged**
