### PR TITLE
Update to Unicode 12.1 with ucd-generate

### PR DESCRIPTION
**Pull request by wezm**
This PR replaces `unicode.py` generated tables with tables generated by the Rust tool `ucd-generate` and updates the generated tables to Unicode 12.1.

Specifically it uses [our (YesLogic) fork of `ucd-generate`](https://crates.io/crates/yeslogic-ucd-generate) which we've extended with support for generating `bidi-class` tables.

### CODE REVIEW

**Comment by Manishearth** [comment]
I'm not very comfortable to moving the specifics of the generation logic out of tree. It would make sense to have a shared library that can parse unicode files and generate various kinds of tables (indeed, the various python scripts used by unicode crates are largely the same code with some differences) which each crate uses with some tailoring, but I'm not sure it makes sense to have the entire generation out of tree.

**Comment by Manishearth** [comment]
There are also a lot of unicode crates using generation scripts like this and we should come up with a unified plan for them. Some do a bunch more work than others, for example unicode-script has a lot of custom logic it uses for generating the scriptextensions mappings.

**Comment by Manishearth** [comment]
That said I'm kinda okay in this specific case (though we should use upstream) since the bidi tables are quite straightforward.

**Comment by wezm** [comment]
> though we should use upstream

My earlier PR to ucd-generate has remained open without comment for more than a month so I decided to move forward with our forked version for now.

**Comment by Manishearth** [comment]
For now perhaps we can just land an update to 12.1 while we figure out the right strategy for all the other crates to use?

**Pull request closed without merging**
